export default {
  configs: [
    {
      "code": "ar",
      "en": "Arabic",
      "zh_Hans": "阿拉伯语",
      "zh_Hant": "阿拉伯語",
      "es": "Árabe",
      "fr": "Arabe",
      "pt": "Árabe",
      "ru": "Арабский",
      "de": "Arabisch",
      "ja": "アラビア語",
      "it": "Arabo",
      "ko": "아랍어"
    },
    {
      "code": "bn",
      "en": "Bengali",
      "zh_Hans": "孟加拉语",
      "zh_Hant": "孟加拉語",
      "es": "Bengalí",
      "fr": "Bengali",
      "pt": "Bengali",
      "ru": "Бенгальский",
      "de": "Bengalisch",
      "ja": "ベンガル語",
      "it": "Bengalese",
      "ko": "벵골어"
    },
    {
      "code": "bg",
      "en": "Bulgarian",
      "zh_Hans": "保加利亚语",
      "zh_Hant": "保加利亞語",
      "es": "Búlgaro",
      "fr": "Bulgare",
      "pt": "Búlgaro",
      "ru": "Болгарский",
      "de": "Bulgarisch",
      "ja": "ブルガリア語",
      "it": "Bulgaro",
      "ko": "불가리아어"
    },
    {
      "code": "zh_Hans",
      "en": "Chinese (Simplified)",
      "zh_Hans": "简体中文",
      "zh_Hant": "簡體中文",
      "es": "Chino (simplificado)",
      "fr": "Chinois (simplifié)",
      "pt": "Chinês (simplificado)",
      "ru": "Китайский (упрощенный)",
      "de": "Chinesisch (vereinfacht)",
      "ja": "中国語（簡体字）",
      "it": "Cinese (semplificato)",
      "ko": "중국어(간체)"
    },
    {
      "code": "zh_Hant",
      "en": "Chinese (Traditional)",
      "zh_Hans": "繁体中文",
      "zh_Hant": "繁體中文",
      "es": "Chino (tradicional)",
      "fr": "Chinois (traditionnel)",
      "pt": "Chinês (tradicional)",
      "ru": "Китайский (традиционный)",
      "de": "Chinesisch (traditionell)",
      "ja": "中国語（繁体字）",
      "it": "Cinese (tradizionale)",
      "ko": "중국어(번체)"
    },
    {
      "code": "hr",
      "en": "Croatian",
      "zh_Hans": "克罗地亚语",
      "zh_Hant": "克羅地亞語",
      "es": "Croata",
      "fr": "Croate",
      "pt": "Croata",
      "ru": "Хорватский",
      "de": "Kroatisch",
      "ja": "クロアチア語",
      "it": "Croato",
      "ko": "크로아티아어"
    },
    {
      "code": "cs",
      "en": "Czech",
      "zh_Hans": "捷克语",
      "zh_Hant": "捷克語",
      "es": "Checo",
      "fr": "Tchèque",
      "pt": "Checo",
      "ru": "Чешский",
      "de": "Tschechisch",
      "ja": "チェコ語",
      "it": "Ceco",
      "ko": "체코어"
    },
    {
      "code": "da",
      "en": "Danish",
      "zh_Hans": "丹麦语",
      "zh_Hant": "丹麥語",
      "es": "Danés",
      "fr": "Danois",
      "pt": "Dinamarquês",
      "ru": "Датский",
      "de": "Dänisch",
      "ja": "デンマーク語",
      "it": "Danese",
      "ko": "덴마크어"
    },
    {
      "code": "nl",
      "en": "Dutch",
      "zh_Hans": "荷兰语",
      "zh_Hant": "荷蘭語",
      "es": "Neerlandés",
      "fr": "Néerlandais",
      "pt": "Holandês",
      "ru": "Голландский",
      "de": "Niederländisch",
      "ja": "オランダ語",
      "it": "Olandese",
      "ko": "네덜란드어"
    },
    {
      "code": "en",
      "en": "English",
      "zh_Hans": "英语",
      "zh_Hant": "英語",
      "es": "Inglés",
      "fr": "Anglais",
      "pt": "Inglês",
      "ru": "Английский",
      "de": "Englisch",
      "ja": "英語",
      "it": "Inglese",
      "ko": "영어"
    },
    {
      "code": "et",
      "en": "Estonian",
      "zh_Hans": "爱沙尼亚语",
      "zh_Hant": "愛沙尼亞語",
      "es": "Estonio",
      "fr": "Estonien",
      "pt": "Estoniano",
      "ru": "Эстонский",
      "de": "Estnisch",
      "ja": "エストニア語",
      "it": "Estone",
      "ko": "에스토니아어"
    },
    {
      "code": "fi",
      "en": "Finnish",
      "zh_Hans": "芬兰语",
      "zh_Hant": "芬蘭語",
      "es": "Finlandés",
      "fr": "Finnois",
      "pt": "Finlandês",
      "ru": "Финский",
      "de": "Finnisch",
      "ja": "フィンランド語",
      "it": "Finlandese",
      "ko": "핀란드어"
    },
    {
      "code": "fr",
      "en": "French",
      "zh_Hans": "法语",
      "zh_Hant": "法語",
      "es": "Francés",
      "fr": "Français",
      "pt": "Francês",
      "ru": "Французский",
      "de": "Französisch",
      "ja": "フランス語",
      "it": "Francese",
      "ko": "프랑스어"
    },
    {
      "code": "de",
      "en": "German",
      "zh_Hans": "德语",
      "zh_Hant": "德語",
      "es": "Alemán",
      "fr": "Allemand",
      "pt": "Alemão",
      "ru": "Немецкий",
      "de": "Deutsch",
      "ja": "ドイツ語",
      "it": "Tedesco",
      "ko": "독일어"
    },
    {
      "code": "el",
      "en": "Greek",
      "zh_Hans": "希腊语",
      "zh_Hant": "希臘語",
      "es": "Griego",
      "fr": "Grec",
      "pt": "Grego",
      "ru": "Греческий",
      "de": "Griechisch",
      "ja": "ギリシャ語",
      "it": "Greco",
      "ko": "그리스어"
    },
    {
      "code": "iw",
      "en": "Hebrew",
      "zh_Hans": "希伯来语",
      "zh_Hant": "希伯來語",
      "es": "Hebreo",
      "fr": "Hébreu",
      "pt": "Hebraico",
      "ru": "Иврит",
      "de": "Hebräisch",
      "ja": "ヘブライ語",
      "it": "Ebraico",
      "ko": "히브리어"
    },
    {
      "code": "hi",
      "en": "Hindi",
      "zh_Hans": "印地语",
      "zh_Hant": "印地語",
      "es": "Hindi",
      "fr": "Hindi",
      "pt": "Hindi",
      "ru": "Хинди",
      "de": "Hindi",
      "ja": "ヒンディー語",
      "it": "Hindi",
      "ko": "힌디어"
    },
    {
      "code": "hu",
      "en": "Hungarian",
      "zh_Hans": "匈牙利语",
      "zh_Hant": "匈牙利語",
      "es": "Húngaro",
      "fr": "Hongrois",
      "pt": "Húngaro",
      "ru": "Венгерский",
      "de": "Ungarisch",
      "ja": "ハンガリー語",
      "it": "Ungherese",
      "ko": "헝가리어"
    },
    {
      "code": "id",
      "en": "Indonesian",
      "zh_Hans": "印度尼西亚语",
      "zh_Hant": "印尼語",
      "es": "Indonesio",
      "fr": "Indonésien",
      "pt": "Indonésio",
      "ru": "Индонезийский",
      "de": "Indonesisch",
      "ja": "インドネシア語",
      "it": "Indonesiano",
      "ko": "인도네시아어"
    },
    {
      "code": "it",
      "en": "Italian",
      "zh_Hans": "意大利语",
      "zh_Hant": "意大利語",
      "es": "Italiano",
      "fr": "Italien",
      "pt": "Italiano",
      "ru": "Итальянский",
      "de": "Italienisch",
      "ja": "イタリア語",
      "it": "Italiano",
      "ko": "이탈리아어"
    },
    {
      "code": "ja",
      "en": "Japanese",
      "zh_Hans": "日语",
      "zh_Hant": "日語",
      "es": "Japonés",
      "fr": "Japonais",
      "pt": "Japonês",
      "ru": "Японский",
      "de": "Japanisch",
      "ja": "日本語",
      "it": "Giapponese",
      "ko": "일본어"
    },
    {
      "code": "ko",
      "en": "Korean",
      "zh_Hans": "韩语",
      "zh_Hant": "韓語",
      "es": "Coreano",
      "fr": "Coréen",
      "pt": "Coreano",
      "ru": "Корейский",
      "de": "Koreanisch",
      "ja": "韓国語",
      "it": "Coreano",
      "ko": "한국어"
    }
  ]
}
